version = "1.21.5"

curse = [
#        256717, # clumps
    #    846196, # boosted-brightness-fabric
#    579192, # farsight
#    326652, # cupboard - farsight dependency
]

modrinth = [
    "sodium",
    "sodium-extra",
#    "continuity", not yet updated
    "modmenu",
#    "cull-leaves",
    "reeses-sodium-options",
    "entityculling",
    "advanced-chat",
    "appleskin",
#    "carpet", maintained, but not updated in modrinth
#    "carpet-extra",
    "dynamic-fps",
#    "ebe",
#    "exordium",
#    "gadget",
    "gamma-utils",
    "in-game-account-switcher",
    "iris",
    "jade",
    "forcecloseworldloadingscreen",
#    "lighty",
#    "modernfix",
    "mouse-tweaks",
#    "nbttooltip", wait for modrinth release, until then use my fork
    "obsidianui",
    "rrls",
    "rei",
    "roughly-enough-professions-rep",
#    "ryoamiclights",
    "simple-voice-chat",
    "threadtweak",
#    "tooltipfix",
    "viafabricplus",
    "xaeros-minimap",
#    "xaeros-world-map", not yet updated
    "yacl",
    "zoomify",
    "fabric-language-kotlin",
#    "tweakeroo",
#    "minihud",
#    "litematica",
    "clumps"
]