version = "1.21.1"

curse = [
#    256717, # clumps
    #    846196, # boosted-brightness-fabric
    1068882, # malilib
    1068908, # litematica
    1068914, # minihud
    1068922, # tweakeroo
    579192, # farsight
    #    274816, # nbt-tooltip
]

modrinth = [
    "sodium",
    "indium",
    "sodium-extra",
    "continuity",
    "modmenu",
    "cull-leaves",
    "reeses-sodium-options",
    "entityculling",
    "advanced-chat",
    "appleskin",
#    "carpet", maintained, but not updated in modrinth
#    "carpet-extra",
    "dynamic-fps",
    "ebe",
    #    "exordium", seems to not be maintained anymore,
    "gadget",
    "gamma-utils",
    "in-game-account-switcher",
    "iris",
    "jade",
    "forcecloseworldloadingscreen",
    "lighty",
    "modernfix",
    "mouse-tweaks",
    "nbttooltip",
    "obsidianui",
    "rrls",
    "rei",
    "roughly-enough-professions-rep",
    "ryoamiclights",
    "simple-voice-chat",
    "threadtweak",
    "tooltipfix",
    "viafabricplus",
    "xaeros-minimap",
    "xaeros-world-map",
    "yacl"
]