version = "1.21.11"

curse = [
#        256717, # clumps
    #    846196, # boosted-brightness-fabric
#    579192, # farsight
#    326652, # cupboard - farsight dependency
]

modrinth = [
    "sodium",
    "sodium-extra",
    "continuity",
    "modmenu",
    "cull-leaves",
    "reeses-sodium-options",
    "entityculling",
    "advanced-chat",
    "appleskin",
#    "carpet", maintained, but not updated in modrinth
#    "carpet-extra",
    "dynamic-fps",
#    "ebe",
#    "exordium",
#    "gadget",
    "gamma-utils",
    "in-game-account-switcher",
    "iris",
    "item-scroller",
    "jade",
    "jei",
    "forcecloseworldloadingscreen",
    "lambdynamiclights",
    "lighty",
#    "modernfix",
    "mouse-tweaks",
#    "obsidianui",
    "rrls",
#    "rei",
#    "roughly-enough-professions-rep",
    "simple-voice-chat",
#    "threadtweak",
#    "tooltipfix",
    "viafabricplus",
    "xaeros-minimap",
#    "xaeros-world-map", not yet updated
#    "yacl",
#    "zoomify",
#    "fabric-language-kotlin",
#    "tweakeroo",
#    "minihud",
#    "litematica",
#    "clumps"
]