version = "1.21.3"

curse = [
    #    256717, # clumps
    #    846196, # boosted-brightness-fabric
#    579192, # farsight
#    326652, # cupboard - farsight dependency
    #    274816, # nbt-tooltip
]

modrinth = [
    "sodium",
    "sodium-extra",
    "continuity",
    "modmenu",
    "cull-leaves",
    "reeses-sodium-options",
    "entityculling",
    "advanced-chat",
    "appleskin",
#    "carpet", maintained, but not updated in modrinth
#    "carpet-extra",
    "dynamic-fps",
#    "ebe",
#    "exordium",
#    "gadget",
    "gamma-utils",
    "in-game-account-switcher",
    "iris",
    "jade",
    "forcecloseworldloadingscreen",
    "lighty",
#    "modernfix",
    "mouse-tweaks",
    "nbttooltip",
    "obsidianui",
    "rrls",
    "rei",
    "roughly-enough-professions-rep",
#    "ryoamiclights",
    "simple-voice-chat",
    "threadtweak",
#    "tooltipfix",
    "viafabricplus",
    "xaeros-minimap",
    "xaeros-world-map",
    "yacl",
    "zoomify",
    "fabric-language-kotlin",
    "tweakeroo",
    "minihud",
    "litematica"
]