[libraries]
clumps = { group = "maven.modrinth", name = "clumps", version = "8BikzIOh" }
fabric-api = { group = "maven.modrinth", name = "fabric-api", version = "dQ3p80zK" }
litematica = { group = "maven.modrinth", name = "litematica", version = "dnpbV1lI" }
malilib = { group = "maven.modrinth", name = "malilib", version = "Uddakc3M" }
minihud = { group = "maven.modrinth", name = "minihud", version = "lRYtM6ZP" }
tweakeroo = { group = "maven.modrinth", name = "tweakeroo", version = "ojIuYAA7" }
fabric-language-kotlin = { group = "maven.modrinth", name = "fabric-language-kotlin", version = "LcgnDDmT" }
zoomify = { group = "maven.modrinth", name = "zoomify", version = "jF5geVmV" }
yacl = { group = "maven.modrinth", name = "yacl", version = "ORi1nScg" }
xaeros-minimap = { group = "maven.modrinth", name = "xaeros-minimap", version = "hztxb2W2" }
viafabricplus = { group = "maven.modrinth", name = "viafabricplus", version = "aIY3u1Xo" }
simple-voice-chat = { group = "maven.modrinth", name = "simple-voice-chat", version = "359H2vUG" }
roughly-enough-professions-rep = { group = "maven.modrinth", name = "roughly-enough-professions-rep", version = "SV9mnzSJ" }
rei = { group = "maven.modrinth", name = "rei", version = "CkkZK8ao" }
cloth-config = { group = "maven.modrinth", name = "cloth-config", version = "qMxkrrmq" }
architectury-api = { group = "maven.modrinth", name = "architectury-api", version = "9eRDsZKH" }
rrls = { group = "maven.modrinth", name = "rrls", version = "76XHcrde" }
forge-config-api-port = { group = "maven.modrinth", name = "forge-config-api-port", version = "IKHTwwTv" }
mouse-tweaks = { group = "maven.modrinth", name = "mouse-tweaks", version = "ULOi34Uh" }
lighty = { group = "maven.modrinth", name = "lighty", version = "uIAKmLgY" }
lambdynamiclights = { group = "maven.modrinth", name = "lambdynamiclights", version = "QEjgcnZG" }
forcecloseworldloadingscreen = { group = "maven.modrinth", name = "forcecloseworldloadingscreen", version = "mw6hZ9rT" }
jade = { group = "maven.modrinth", name = "jade", version = "nCbsPtPw" }
item-scroller = { group = "maven.modrinth", name = "item-scroller", version = "DlBrZwem" }
iris = { group = "maven.modrinth", name = "iris", version = "r1MZ1Bpv" }
sodium = { group = "maven.modrinth", name = "sodium", version = "sFfidWgd" }
in-game-account-switcher = { group = "maven.modrinth", name = "in-game-account-switcher", version = "LgfVj4KS" }
gamma-utils = { group = "maven.modrinth", name = "gamma-utils", version = "QA7Jdm3C" }
gadget = { group = "maven.modrinth", name = "gadget", version = "h6cSkqZr" }
owo-lib = { group = "maven.modrinth", name = "owo-lib", version = "dZPuIa4j" }
dynamic-fps = { group = "maven.modrinth", name = "dynamic-fps", version = "WfSXh637" }
appleskin = { group = "maven.modrinth", name = "appleskin", version = "8sbiz1lS" }
advanced-chat = { group = "maven.modrinth", name = "advanced-chat", version = "wiedCy7A" }
entityculling = { group = "maven.modrinth", name = "entityculling", version = "s6K5qu4u" }
reeses-sodium-options = { group = "maven.modrinth", name = "reeses-sodium-options", version = "nUGhyPwZ" }
cull-leaves = { group = "maven.modrinth", name = "cull-leaves", version = "7lE1b6Ao" }
midnightlib = { group = "maven.modrinth", name = "midnightlib", version = "VoGY1DpA" }
modmenu = { group = "maven.modrinth", name = "modmenu", version = "e0mxOOIE" }
placeholder-api = { group = "maven.modrinth", name = "placeholder-api", version = "T5pDJV1K" }
continuity = { group = "maven.modrinth", name = "continuity", version = "7JbPpQnu" }
sodium-extra = { group = "maven.modrinth", name = "sodium-extra", version = "8CGTW5B3" }

[bundles]
mods = [
    "clumps",
    "fabric-api",
    "litematica",
    "malilib",
    "minihud",
    "tweakeroo",
    "fabric-language-kotlin",
    "zoomify",
    "yacl",
    "xaeros-minimap",
    "viafabricplus",
    "simple-voice-chat",
    "roughly-enough-professions-rep",
    "rei",
    "cloth-config",
    "architectury-api",
    "rrls",
    "forge-config-api-port",
    "mouse-tweaks",
    "lighty",
    "lambdynamiclights",
    "forcecloseworldloadingscreen",
    "jade",
    "item-scroller",
    "iris",
    "sodium",
    "in-game-account-switcher",
    "gamma-utils",
    "gadget",
    "owo-lib",
    "dynamic-fps",
    "appleskin",
    "advanced-chat",
    "entityculling",
    "reeses-sodium-options",
    "cull-leaves",
    "midnightlib",
    "modmenu",
    "placeholder-api",
    "continuity",
    "sodium-extra",
]
