[libraries]
clumps = { group = "maven.modrinth", name = "clumps", version = "nH8YfRWs" }
fabric-api = { group = "maven.modrinth", name = "fabric-api", version = "ZOyJh09R" }
fabric-language-kotlin = { group = "maven.modrinth", name = "fabric-language-kotlin", version = "E4WyjCxJ" }
zoomify = { group = "maven.modrinth", name = "zoomify", version = "RKRjd2h1" }
yacl = { group = "maven.modrinth", name = "yacl", version = "5yBEzonb" }
xaeros-minimap = { group = "maven.modrinth", name = "xaeros-minimap", version = "UV9Vstfl" }
viafabricplus = { group = "maven.modrinth", name = "viafabricplus", version = "3qZVBjMD" }
threadtweak = { group = "maven.modrinth", name = "threadtweak", version = "IvtlnXcT" }
simple-voice-chat = { group = "maven.modrinth", name = "simple-voice-chat", version = "OzXC5Efi" }
roughly-enough-professions-rep = { group = "maven.modrinth", name = "roughly-enough-professions-rep", version = "3PZRWH2m" }
rei = { group = "maven.modrinth", name = "rei", version = "HolhxWBq" }
architectury-api = { group = "maven.modrinth", name = "architectury-api", version = "ImZUcNzP" }
cloth-config = { group = "maven.modrinth", name = "cloth-config", version = "qA00xo1O" }
rrls = { group = "maven.modrinth", name = "rrls", version = "ktUVJ0iP" }
forge-config-api-port = { group = "maven.modrinth", name = "forge-config-api-port", version = "mlQdrgSO" }
obsidianui = { group = "maven.modrinth", name = "obsidianui", version = "2Tc3JJ8z" }
mouse-tweaks = { group = "maven.modrinth", name = "mouse-tweaks", version = "m8rwZENW" }
forcecloseworldloadingscreen = { group = "maven.modrinth", name = "forcecloseworldloadingscreen", version = "G95MOUIu" }
jade = { group = "maven.modrinth", name = "jade", version = "EE9Gk8ly" }
iris = { group = "maven.modrinth", name = "iris", version = "U6evbjd0" }
sodium = { group = "maven.modrinth", name = "sodium", version = "DA250htH" }
in-game-account-switcher = { group = "maven.modrinth", name = "in-game-account-switcher", version = "96FYffnc" }
gamma-utils = { group = "maven.modrinth", name = "gamma-utils", version = "V3xn4HAL" }
dynamic-fps = { group = "maven.modrinth", name = "dynamic-fps", version = "plAPgk28" }
appleskin = { group = "maven.modrinth", name = "appleskin", version = "VfjnbBAT" }
advanced-chat = { group = "maven.modrinth", name = "advanced-chat", version = "CEJSc93h" }
entityculling = { group = "maven.modrinth", name = "entityculling", version = "29GV7fju" }
reeses-sodium-options = { group = "maven.modrinth", name = "reeses-sodium-options", version = "KoUrx3jJ" }
modmenu = { group = "maven.modrinth", name = "modmenu", version = "T7GjZmwP" }
placeholder-api = { group = "maven.modrinth", name = "placeholder-api", version = "AkMeBicV" }
sodium-extra = { group = "maven.modrinth", name = "sodium-extra", version = "E5w6eZNE" }

[bundles]
mods = [
    "clumps",
    "fabric-api",
    "fabric-language-kotlin",
    "zoomify",
    "yacl",
    "xaeros-minimap",
    "viafabricplus",
    "threadtweak",
    "simple-voice-chat",
    "roughly-enough-professions-rep",
    "rei",
    "architectury-api",
    "cloth-config",
    "rrls",
    "forge-config-api-port",
    "obsidianui",
    "mouse-tweaks",
    "forcecloseworldloadingscreen",
    "jade",
    "iris",
    "sodium",
    "in-game-account-switcher",
    "gamma-utils",
    "dynamic-fps",
    "appleskin",
    "advanced-chat",
    "entityculling",
    "reeses-sodium-options",
    "modmenu",
    "placeholder-api",
    "sodium-extra",
]
