[libraries]
xaeros-world-map = { group = "maven.modrinth", name = "xaeros-world-map", version = "2lbtkEPK" }
fabric-api = { group = "maven.modrinth", name = "fabric-api", version = "htRy7kbI" }
xaeros-minimap = { group = "maven.modrinth", name = "xaeros-minimap", version = "N5jBKzC0" }
viafabricplus = { group = "maven.modrinth", name = "viafabricplus", version = "2low4Dcu" }
tooltipfix = { group = "maven.modrinth", name = "tooltipfix", version = "B2L4LeMV" }
threadtweak = { group = "maven.modrinth", name = "threadtweak", version = "pc1QuN32" }
simple-voice-chat = { group = "maven.modrinth", name = "simple-voice-chat", version = "r7e564VW" }
roughly-enough-professions-rep = { group = "maven.modrinth", name = "roughly-enough-professions-rep", version = "q9eTEsvC" }
rei = { group = "maven.modrinth", name = "rei", version = "Jhw0fDTs" }
architectury-api = { group = "maven.modrinth", name = "architectury-api", version = "kVjQWX0l" }
cloth-config = { group = "maven.modrinth", name = "cloth-config", version = "eBZiZ9NS" }
rrls = { group = "maven.modrinth", name = "rrls", version = "hAO2J982" }
mouse-tweaks = { group = "maven.modrinth", name = "mouse-tweaks", version = "mjuG4AYd" }
modernfix = { group = "maven.modrinth", name = "modernfix", version = "lQs9avbD" }
light-overlay = { group = "maven.modrinth", name = "light-overlay", version = "xHBA44Di" }
lambdynamiclights = { group = "maven.modrinth", name = "lambdynamiclights", version = "mrQ8ZiyU" }
forcecloseworldloadingscreen = { group = "maven.modrinth", name = "forcecloseworldloadingscreen", version = "fyVeLayX" }
jade = { group = "maven.modrinth", name = "jade", version = "fNHCa6bl" }
iris = { group = "maven.modrinth", name = "iris", version = "kGdJ11Rt" }
sodium = { group = "maven.modrinth", name = "sodium", version = "4GyXKCLd" }
exordium = { group = "maven.modrinth", name = "exordium", version = "WyhKYeMf" }
ebe = { group = "maven.modrinth", name = "ebe", version = "eIFo7wvq" }
dynamic-fps = { group = "maven.modrinth", name = "dynamic-fps", version = "shfvdKKK" }
carpet-extra = { group = "maven.modrinth", name = "carpet-extra", version = "APnGg1O6" }
carpet = { group = "maven.modrinth", name = "carpet", version = "yYzR60Xd" }
appleskin = { group = "maven.modrinth", name = "appleskin", version = "pmFyu3Sz" }
advanced-chat = { group = "maven.modrinth", name = "advanced-chat", version = "tBkISdKZ" }
entityculling = { group = "maven.modrinth", name = "entityculling", version = "7JR5qJ8f" }
auth-me = { group = "maven.modrinth", name = "auth-me", version = "HhWVxCH0" }
reeses-sodium-options = { group = "maven.modrinth", name = "reeses-sodium-options", version = "fkLiGoHs" }
cull-less-leaves = { group = "maven.modrinth", name = "cull-less-leaves", version = "TFvkv8XK" }
yacl = { group = "maven.modrinth", name = "yacl", version = "StXMrAsz" }
modmenu = { group = "maven.modrinth", name = "modmenu", version = "w3icASIi" }
continuity = { group = "maven.modrinth", name = "continuity", version = "JXhQlDZl" }
sodium-extra = { group = "maven.modrinth", name = "sodium-extra", version = "M0ndiav7" }
indium = { group = "maven.modrinth", name = "indium", version = "Aouse6P7" }
nbt-tooltip = { group = "curse.maven", name = "nbt-tooltip-274816", version = "5168841" }
tweakeroo = { group = "curse.maven", name = "tweakeroo-297344", version = "5096820" }
malilib = { group = "curse.maven", name = "malilib-303119", version = "5096807" }
minihud = { group = "curse.maven", name = "minihud-244260", version = "5096818" }
litematica = { group = "curse.maven", name = "litematica-308892", version = "5170070" }
clumps = { group = "curse.maven", name = "clumps-256717", version = "5025925" }

[bundles]
mods = [
    "xaeros-world-map",
    "fabric-api",
    "xaeros-minimap",
    "viafabricplus",
    "tooltipfix",
    "threadtweak",
    "simple-voice-chat",
    "roughly-enough-professions-rep",
    "rei",
    "architectury-api",
    "cloth-config",
    "rrls",
    "mouse-tweaks",
    "modernfix",
    "light-overlay",
    "lambdynamiclights",
    "forcecloseworldloadingscreen",
    "jade",
    "iris",
    "sodium",
    "exordium",
    "ebe",
    "dynamic-fps",
    "carpet-extra",
    "carpet",
    "appleskin",
    "advanced-chat",
    "entityculling",
    "auth-me",
    "reeses-sodium-options",
    "cull-less-leaves",
    "yacl",
    "modmenu",
    "continuity",
    "sodium-extra",
    "indium",
    "nbt-tooltip",
    "tweakeroo",
    "malilib",
    "minihud",
    "litematica",
    "clumps",
]
